version: "3.8"
services:
  server:
    build: ./app
    env_file:
      - ./app/.env
    command: python3 main.py
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
